# Generated by Django 3.1.6 on 2021-02-05 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0002_auto_20210202_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
