# Generated by Django 3.1.6 on 2021-02-05 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list_app', '0003_auto_20210205_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
